### ISSUE TITLE
Possibility way to refactoring

### ISSUE THREAD

**Issue by superkomar** [lmd-luxoft/lab-4-inheritance-superkomar#2]
Сделать класс ChessFigure абстракным классом с абстракнтым методом Move

Для каждой фигуры создать класс наследующий ChessFigure и реаизующий Move

Далее два пути:
1) Сделать отдельный метод, который по енаму возвращает определенный инстанс ChessFigure
2) Создавать конкретный инстанс фигуры и звать Move

**Comment by paveltsytovich** [comment]
Направление мысли верное. С точки зрения тестов, второй путь предпочтительней
